### ISSUE TITLE
Latest ubuntu install error

### ISSUE THREAD

**Issue by Nortag82** [LibreBooking/app#229] opened 2023-09-16 21:40 UTC
Hello,

I am fairly new on ubuntu and trying to install librebooking on it. This is what i am testing so far, with no luck. Just getting 500 error.

Its a new ubuntu image. checked php.ini for session autostart set to "0". Any support would be apreciated. I tried docker, but never used dicker and got nowhere with it. :) Latest stable release used.

Any support would apreciated. 

*******************
sudo apt-get install apache2 mysql-server mysql-client php php-cgi libapache2-mod-php php-common php-pear php-mbstring php-text-captcha wget unzip -y
sudo apt install ldap-utils
sudo systemctl start mysql
sudo systemctl start apache2
sudo systemctl enable mysql
sudo systemctl enable apache2
sudo mysql_secure_installation

sudo mysql -u root -p

CREATE DATABASE librebooking;
CREATE USER 'sj'@'localhost' IDENTIFIED BY 'sj';
GRANT ALL PRIVILEGES ON librebooking.* TO 'sj'@'localhost';
FLUSH PRIVILEGES;
exit

sudo wget http://192.168.1.57/wp-content/uploads/Upload/librebooking.zip
sudo unzip librebooking.zip
sudo mv librebooking /var/www/html/
sudo chown -R www-data:www-data /var/www/html/librebooking
sudo chmod -R 0755 /var/www/html/librebooking/tpl
sudo chmod -R 0755 /var/www/html/librebooking/tpl_c

sudo nano /etc/apache2/sites-available/librebooking.conf

*******************************************************************
<VirtualHost *:80>
    DocumentRoot /var/www/html/librebooking
    <Directory /var/www/html/librebooking>
        Options FollowSymLinks
        AllowOverride Limit Options FileInfo
        DirectoryIndex index.php
        Require all granted
    </Directory>
    <Directory /var/www/html/librebooking>
        Options FollowSymLinks
        Require all granted
    </Directory>
</VirtualHost>
******************************************************************

sudo a2ensite librebooking
sudo a2enmod rewrite
sudo a2enmod headers
sudo systemctl restart apache2

sudo cp /var/www/html/librebooking/config/config.dist.php /var/www/html/librebooking/config/config.php

sudo nano /var/www/html/librebooking/config/config.php

//script url "http://192.168.1.50/librebooking/Web/"     error 500
//install PW set
//adm email set

tried http://192.168.1.50/librebooking/Web/install  just getting error 500 html.

sudo mysql librebooking < /var/www/html/librebooking/database_schema/create-schema.sql
sudo mysql librebooking < /var/www/html/librebooking/database_schema/create-data.sql

*********************************************************************

**Comment by Nortag82** [comment] 2023-09-16 23:09
when I use an older version, i get the webpage up, but saying "unknown error" 2.8.5.4

**Comment by KarolUAM** [comment] 2023-09-17 13:07
Do you using Ubuntu 22.04 server? If yes, the problem is MySQL 8 (mysql 8 is default part of ubuntu 22.04 server) . Libre Booking not working with MySQL 8.

**Comment by Nortag82** [comment] 2023-09-17 19:44
> Do you using Ubuntu 22.04 server? If yes, the problem is MySQL 8 (mysql 8 is default part of ubuntu 22.04 server) . Libre Booking not working with MySQL 8.

aha? so use mariadb? Thank you so much for the reply.

**Comment by KarolUAM** [comment] 2023-09-19 06:39
Try mysql 5.7 - if working, the problem is with mysql8. Best,

Karol

**Comment by Nortag82** [comment] 2023-09-19 21:25
so i managed to change the log path, 

but when logging in with admin/passeord or user/password, it just goes straight back to the login screen. when pressing "view schedule" i can see the test entries from the sample data. 

log shows:

[2023-09-19T21:21:23.348252+00:00] app.INFO: [User=  ()] Trying to log in as: admin [File=/var/www/html/librebooking/lib/Application/Authentication/Authentication.php,Line=8>
[2023-09-19T21:21:23.353059+00:00] app.INFO: [User=  ()] User was found: admin [File=/var/www/html/librebooking/lib/Application/Authentication/Authentication.php,Line=89] []>
[2023-09-19T21:21:23.353218+00:00] app.INFO: [User=  ()] User: admin, was validated: 1 [File=/var/www/html/librebooking/lib/Application/Authentication/Authentication.php,Lin>
<,Line=106] [] []

Any ideas?

**Comment by Nortag82** [comment] 2023-09-19 22:13
changed $conf['settings']['script.url'] = 'http://10.252.144.124/librebooking/Web/';
to:
$conf['settings']['script.url'] = 'http:';

and it works now. thanks to @flipside37 's post

**Comment by colisee** [comment] 2023-09-27 07:19
Hi @Nortag82 

If you solved the issue, could you please close it?
Thanks.

**Closed** 2023-10-02 13:08 UTC
